# version: '3.8'

# services:
#   nextjs-dev:
#     container_name: nextjs-dev
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - '3000:3000'
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     command: npm run dev

#   nextjs-prod:
#     container_name: nextjs-prod
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3001:3000'
#     environment:
#       - NODE_ENV=production
